// src/app/layout.tsx

import { Metadata } from 'next';

// Remove a diretiva "use client" do layout.tsx
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <header>
        {/* O seu Header aqui */}
      </header>
      <main>{children}</main>
      <footer>
        {/* O seu Footer aqui */}
      </footer>
    </div>
  );
}
